/**
 ******************************************************************************
 * 
 * Copyright (c) 2025 KaiserEngineering, LLC
 * Author Matthew Kaiser 
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 ******************************************************************************
 */

#include "lib_pid.h"

const uint32_t pid_list[] = {
    MODE1_ACCEL_PEDAL_POS_UUID,
    MODE1_AIR_FUEL_RATIO_OXYGEN_SENSOR_1_UUID,
    MODE22_AMBIENT_AIR_TEMP_UUID,
    MODE1_BAROMETRIC_PRESSURE_UUID,
    MODE1_BOOST_UUID,
    CALC1_BOOST_VACUUM_UUID,
    SNIFF_BRAKE_PEDAL_STATUS_UUID,
    MODE1_CALC_ENGINE_LOAD_UUID,
    MODE22_CATALYTIC_TEMPERATURE_UUID,
    MODE22_CHARGE_AIR_TEMP_ST_UUID,
    MODE1_COMMANDED_AIR_FUEL_RATIO_UUID,
    SNIFF_CRUISE_CONTROL_CAN_BUTTON_UUID,
    SNIFF_CRUISE_CONTROL_OFF_BUTTON_UUID,
    CALC1_CRUISE_CONTROL_OFF_BUTTON_TOGGLE_UUID,
    SNIFF_CRUISE_CONTROL_ON_BUTTON_UUID,
    SNIFF_CRUISE_CONTROL_RES_BUTTON_UUID,
    SNIFF_CRUISE_CONTROL_SET_MINUS_BUTTON_UUID,
    SNIFF_CRUISE_CONTROL_SET_PLUS_BUTTON_UUID,
    SNIFF_EMERGENCY_BRAKE_STATUS_UUID,
    MODE22_ENGINE_LOAD_UUID,
    MODE1_ENGINE_COOLANT_TEMP_UUID,
    MODE1_ENGINE_SPEED_UUID,
    SNIFF_ENGINE_SPEED_UUID,
    MODE1_FUEL_PRESSURE_UUID,
    MODE1_FUEL_RAIL_PRESSURE_UUID,
    SNIFF_GAUGE_ILLUM_LEVEL_UUID,
    MODE22_IGNITION_CORRECTION_CYLINDER_1_UUID,
    MODE1_INTAKE_AIR_TEMP_UUID,
    MODE22_INTAKE_AIR_TEMP_UUID,
    MODE22_LP_FUEL_DUTY_CYCLE_UUID,
    SNIFF_LATERAL_ACCELERATION_UUID,
    MODE1_LONG_TERM_FUEL_TRIM_BANK_1_UUID,
    MODE1_LONG_TERM_FUEL_TRIM_BANK_2_UUID,
    SNIFF_LONGITUDINAL_ACCELERATION_UUID,
    MODE1_MANIFOLD_ABS_PRESS_UUID,
    MODE22_MANIFOLD_ABS_PRESS_SENSOR_1_VOLT_UUID,
    MODE22_MANIFOLD_CHARGE_TEMP_RS_UUID,
    MODE1_MASS_AIR_FLOW_UUID,
    MODE1_O2_SENSOR_2_VOLTS_UUID,
    MODE22_OCTANE_ADJUST_RATIO_UUID,
    MODE1_OIL_TEMP_UUID,
    SNIFF_REVERSE_STATUS_UUID,
    MODE1_SHORT_TERM_FUEL_TRIM_BANK_1_UUID,
    MODE1_SHORT_TERM_FUEL_TRIM_BANK_2_UUID,
    MODE1_THROTTLE_POSITION_UUID,
    MODE1_TIMING_ADVANCE_UUID,
    MODE22_VCT_EXHAUST_CAM_SOLENOID_DUTY_CYCLE_UUID,
    MODE22_VCT_INTAKE_CAM_SOLENOID_DUTY_CYCLE_UUID,
    MODE1_VEHICLE_SPEED_UUID,
    SNIFF_VEHICLE_STATUS_UUID,
};

uint32_t get_pid_from_list(uint32_t idx) { return pid_list[idx]; }
uint32_t get_pid_list_size(void) { return sizeof(pid_list) / sizeof(pid_list[0]); }
